# Generated by Django 3.2.4 on 2021-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not selected')], default='N', max_length=1),
            preserve_default=False,
        ),
    ]
