# Generated by Django 3.2.4 on 2021-06-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_application_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationLegalEntities',
            fields=[
                ('legal_entity_id', models.UUIDField(primary_key=True, serialize=False)),
                ('legal_entity_name', models.TextField(blank=True, null=True)),
                ('legal_entity_edrpou', models.TextField(blank=True, null=True)),
                ('care_type', models.TextField(blank=True, null=True)),
                ('property_type', models.TextField(blank=True, null=True)),
                ('legal_entity_email', models.EmailField(max_length=254)),
                ('legal_entity_phone', models.TextField(blank=True, null=True)),
                ('legal_entity_owner_name', models.TextField(blank=True, null=True)),
                ('registration_area', models.TextField(blank=True, null=True)),
                ('registration_settlement', models.TextField(blank=True, null=True)),
                ('registration_addresses', models.TextField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lng', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'immunization_legal_entities',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not selected')], default='N', max_length=1),
        ),
    ]
