# Generated by Django 3.2.4 on 2021-06-14 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=30, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='books.author')),
            ],
        ),
    ]
