version: "3.9"
services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: zen
    command: python3 zen.py runserver 0.0.0.0:8000
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "django_db"
      POSTGRES_USER: "django_user"
      POSTGRES_PASSWORD: "postgres"
    
  # celery:
  #   build: celery
